apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '2'
spec:
  auditLogs:
    collection: Auto
  admissionControl:
    enforcement: Enabled
    bypass: BreakGlassAnnotation
  scannerV4:
    scannerComponent: AutoSense
  scanner:
    scannerComponent: Disabled
  clusterName: central
  centralEndpoint: 'central.stackrox.svc.cluster.local:443'
