apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - workload-clusterset.yaml
  - workload-clustersetbinding.yaml

patches:
  - target:
      kind: MultiClusterHub
      name: multiclusterhub
    path: multiclusterhub-patch.yaml
